#!/bin/bash

echo "Project Manager (prj) - Help"
echo ""
echo "Usage:"
echo "  prj list                     - List all available projects"
echo "  prj add <project-name>       - Create a new empty project"
echo "  prj add <git-url>            - Clone a git repository as a project"
echo "  prj add <path/project-name>  - Create a project with path"
echo "  prj add <path/git-url>       - Clone a git repository with path"
echo "  prj rm <project-name>        - Remove a project"
echo "  prj <project-name>           - Open a project in your IDE"
echo "  prj <git-url>                - Clone and open a git repository"
echo "  prj help                     - Show this help message"
echo ""
echo "Configuration:"
echo "  Set PRJ_ROOT environment variable to change projects directory"
echo "  (default: ~/projects)"
echo "  Set PRJ_EDITOR environment variable to change default IDE"
echo "  (default: code - VS Code)"
echo "  prj mv <project1> <project2>  - Rename or move project (like mv command)"
